"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { AuthLayout } from "@/app/login/page";
import { register } from "@/lib/auth-api";

export default function RegisterPage() {
  const [values, setValues] = useState({ email: "", password: "", name: "", phone: "", address: "" }); const [error, setError] = useState(""); const [fieldErrors, setFieldErrors] = useState<Partial<Record<keyof typeof values, string>>>({}); const [loading, setLoading] = useState(false);
  const update = (key: keyof typeof values, value: string) => setValues((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); const nextErrors: Partial<Record<keyof typeof values, string>> = {}; if (!values.email) nextErrors.email = "El email es obligatorio."; else if (!/^\S+@\S+\.\S+$/.test(values.email)) nextErrors.email = "Introduce un email válido."; if (!values.password) nextErrors.password = "La contraseña es obligatoria."; else if (values.password.length < 6) nextErrors.password = "Usa al menos 6 caracteres."; setFieldErrors(nextErrors); if (Object.keys(nextErrors).length) return; setLoading(true); try { await register(values); window.location.assign("/"); } catch (reason) { setError(reason instanceof Error ? reason.message : "No se pudo completar el registro."); } finally { setLoading(false); } }
  return <AuthLayout title="Crea tu cuenta" subtitle="Registra tus datos para entrar al centro operativo."><form onSubmit={submit} className="space-y-3">{(["email", "password", "name", "phone", "address"] as const).map((key) => <label key={key} className="block text-sm font-semibold text-slate-700">{key === "email" ? "Email" : key === "password" ? "Contraseña" : key === "name" ? "Nombre" : key === "phone" ? "Teléfono" : "Dirección"}<input type={key === "password" ? "password" : key === "email" ? "email" : "text"} required={key === "email" || key === "password"} value={values[key]} onChange={(event) => { update(key, event.target.value); setFieldErrors((current) => ({ ...current, [key]: undefined })); }} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 font-normal outline-none focus:border-teal-600" />{fieldErrors[key] && <span className="mt-1 block text-xs font-normal text-rose-700">{fieldErrors[key]}</span>}</label>)}{error && <p role="alert" className="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>}<button disabled={loading} className="w-full rounded-lg bg-teal-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{loading ? "Creando cuenta..." : "Crear cuenta"}</button><p className="text-center text-sm text-slate-500">¿Ya tienes cuenta? <Link className="font-semibold text-teal-700" href="/login">Inicia sesión</Link></p></form></AuthLayout>;
}